/**
 * Mapping from Arabic item names to English image file names
 * This maps the Arabic text in game-data.json to the actual PNG file names
 */

const arabicToEnglishMap = {
  // Common items
  'وردة': 'flower',
  'قطة': 'cat',
  'تفاحة': 'apple',
  'قبعة سوداء': 'hat',
  'كرة حمراء': 'red-balloon-new',
  'كرة': 'red-balloon-new',
  'كرسي': 'chair',
  'طفل': 'child-reading-book',
  'حمامة': 'pigeon',
  'دراجة زرقاء': 'bicycle',
  'دراجة': 'bicycle',
  'سمكة': 'fish',
  'كوب': 'cup',
  'ورقة صفراء': 'yellow',
  'ورقة بيضاء': 'white-carpet',
  'سيارة': 'car',
  'شجرة': 'tree',
  'طاولة': 'table',
  'أرنب أبيض': 'white-rabbit-new',
  'رجل': 'man',
  'سيدة وطفل': 'children-new',
  'خروف': 'sheep',
  'باص أصفر': 'yellow-bus-new',
  'بالونة حمراء': 'red-balloon-new',
  'بالونة': 'red-balloon-new',
  'قطار': 'train',
  'طبق': 'plate',
  'ملعقة': 'spoon',
  'كوب به عصير': 'cup',
  'مقص': 'scissors',
  'مسطرة': 'ruler',
  'برتقالة وتفاحة': 'orange-and-apple-new',
  'شباك': 'window',
  'عصفور في القفص': 'bird',
  'نهر': 'river',
  'قلعة': 'castle',
  'بيتة بيضاء': 'house',
  'علم أحمر وعلم أبيض': 'flag',
  'أبراج الكويت': 'kuwait-towers-new',
  'أذن': 'ear-new',
  'أسد وغزالة': 'lion-and-gazelle-new',
  'أسد': 'lion-new',
  'أسطوانات غاز': 'gas-cylinders-new',
  'أسلاك كهرباء': 'electrical-wires-new',
  'أشارة ضوئية': 'traffic-light-new',
  'أطفال': 'children-new',
  'أمطار': 'rain-new',
  'أهرامات': 'pyramids-new',
  'إبرة': 'needle',
  'بتر': 'battery',
  'بطريق': 'penguin-new',
  'بطيخة': 'watermelon-new',
  'باص أصفر': 'yellow-bus-new',
  'بالونة حمراء': 'red-balloon-new',
  'بالونة': 'red-balloon-new',
  'برتقالة': 'orange-fruit-new',
  'برتقال': 'orange-fruit-new',
  'بطارية': 'battery',
  'تلفاز': 'television',
  'تليفون': 'phone',
  'جريدة': 'newspaper',
  'جزر': 'carrot',
  'جمل أبيض': 'camel',
  'جمل بني وجمل أسود': 'camel',
  'جمل وحشي': 'camel',
  'جندي': 'soldier',
  'جوارب أبيض وأسود': 'socks',
  'حاسوب': 'computer',
  'حافظ': 'wallet',
  'حافلة': 'bus',
  'حذاء أسود': 'shoes',
  'حذاء': 'shoes',
  'حصان أبيض': 'horse',
  'حصان أسود': 'horse',
  'حصان بني': 'horse',
  'حصان': 'horse',
  'حقيبة حمراء وبيضاء': 'bag',
  'حقيبة سوداء': 'bag',
  'حقيبة': 'bag',
  'حليب': 'milk',
  'حمامة بيضاء': 'pigeon',
  'حمامة سوداء': 'pigeon',
  'حمامة': 'pigeon',
  'حوض به سمك': 'pool',
  'حوض': 'pool',
  'خاتم': 'ring',
  'خبز': 'bread',
  'خروف': 'sheep',
  'خضراوات': 'vegetables',
  'خيار': 'cucumber',
  'خياط': 'tailor',
  'دجاجة بيضاء': 'chicken',
  'دجاجة': 'chicken',
  'ديك رومي': 'rooster',
  'ذئب': 'wolf',
  'ذراع': 'arm',
  'ذرة': 'corn',
  'رجل يحلي': 'man',
  'رجل يغير الشارع': 'man-crossing-street',
  'رجل يلبس قبعة': 'man-wearing-hat',
  'رجل': 'man',
  'زرافة': 'giraffe',
  'ساعة يد': 'wrist-watch',
  'ساعة': 'clock',
  'سجادة بيضاء': 'white-carpet',
  'سجادة حمراء': 'red-carpet',
  'سفينة': 'ship',
  'سلة زهور': 'flower-basket',
  'سلة فواكه': 'fruit-basket',
  'سلحفاة': 'turtle',
  'سمكة': 'fish',
  'سنجاب': 'squirrel',
  'سيارة أمام المنزل': 'car',
  'سيارة مطافئ': 'fire-truck',
  'سيارة': 'car',
  'شاحنة': 'truck',
  'شارع': 'street',
  'شاطئ': 'beach',
  'شال أحمر': 'scarf',
  'شباك': 'window',
  'شجرة أمام المنزل': 'tree',
  'شجرة برتقال': 'orange-tree',
  'شجرة بها عصفور': 'tree',
  'شجرة تفاح': 'apple-tree',
  'شجرة': 'tree',
  'شرطي ينظم السير': 'policeman-directing-traffic',
  'شرطي': 'police-car',
  'شمس': 'sun',
  'شمسية خضراء': 'umbrella',
  'شمسية صفراء': 'umbrella',
  'شمعة حمراء': 'candle',
  'شمعة': 'candle',
  'شمعتان حمراء وبيضاء': 'candle',
  'صحن به لحم': 'plate',
  'صندوق مجوهرات': 'jewelry-box',
  'صندوق': 'box',
  'ضفدع': 'frog',
  'طائرة عسكرية': 'airplane',
  'طائرة': 'airplane',
  'طابور الصباح': 'morning-assembly',
  'طالب يحمل علم': 'student-holding-flag',
  'طالب يقرأ كتاب': 'child-reading-book',
  'طاولة عليها تلفزيون': 'table',
  'طاولة عليها لامبريون': 'table',
  'طاولة': 'table',
  'طاووس': 'peacock',
  'طبق': 'plate',
  'طبيب يعالج مريض': 'doctor-examining-patient',
  'طبيب يفحص المريض': 'doctor-examining-patient',
  'طبيب': 'doctor-examining-patient',
  'طفل يحبو على الأرض': 'child',
  'طفل يشرب الحليب': 'child-drinking-milk',
  'طفل يقرأ كتاب': 'child-reading-book',
  'طفل ينام بالسرير': 'child-sleeping-in-bed',
  'طفل': 'child-reading-book',
  'طماطم': 'tomato',
  'عباءة سوداء': 'dress',
  'عربة يسحبها حصان': 'cart',
  'عسل': 'honey',
  'عصفور على الشجرة': 'bird',
  'عصفور في القفص': 'bird',
  'عقرب': 'scorpion',
  'علبة': 'box',
  'علم أحمر وعلم أبيض': 'flag',
  'علم دولة الكويت': 'flag',
  'على سرير': 'bed',
  'عنب': 'grapes',
  'عنكبوت': 'spider',
  'غراب': 'crow',
  'غسالة': 'washing-machine',
  'غواص': 'diver',
  'غيوم بيضاء': 'cloud',
  'فأس': 'axe',
  'فاصولياء': 'beans',
  'فراولة': 'strawberry',
  'فرشاة أسنان': 'toothbrush',
  'فلاح': 'farmer',
  'فلفل أحمر': 'pepper',
  'فيل': 'elephant',
  'قارب أبيض': 'boat',
  'قارب أحمر': 'boat',
  'قبعة سوداء': 'hat',
  'قبعة': 'hat',
  'قطار': 'train',
  'قطة بيضاء': 'cat',
  'قطة سوداء وقطة بيضاء': 'cat',
  'قطة': 'cat',
  'قلعة': 'castle',
  'قلم وأوراق': 'pen',
  'قلم': 'pen',
  'قمر': 'moon',
  'قميص أصفر وقطة بيضاء وقطة سوداء': 't-shirt',
  'قميص': 'shirt',
  'كأس': 'cup',
  'كاس به حليب': 'cup',
  'كاميرا فيديو': 'video-camera',
  'كتاب أبيض وكتاب أحمر': 'book',
  'كتاب': 'book',
  'كرة حمراء': 'red-balloon-new',
  'كرة': 'red-balloon-new',
  'كرسي أحمر وكرسي أزرق': 'chair',
  'كرسي': 'chair',
  'كلب': 'dog',
  'كوب به عصير': 'cup',
  'كوب عصير': 'cup',
  'كوب': 'cup',
  'لبن': 'milk',
  'لعبة': 'doll',
  'ليمون': 'lemon',
  'ليمونة صفراء': 'lemon',
  'ماس': 'diamond',
  'مدفأة': 'heater',
  'مذياع': 'radio',
  'مروج': 'grass',
  'مروحة': 'fan',
  'مسابقة جري': 'race',
  'مسجد': 'mosque',
  'مسطرة': 'ruler',
  'مسلح': 'weapon',
  'مسمار': 'nail',
  'مصباح': 'lamp',
  'مصور': 'photographer',
  'مقص': 'scissors',
  'مكتبة بها': 'library',
  'مكواة': 'iron',
  'مكيف': 'air-conditioner',
  'ملابس': 'clothes',
  'ملعب': 'playground',
  'ملعقة وسكينة': 'spoon',
  'ملعقة': 'spoon',
  'منزل أمامه شجرة': 'house',
  'منزل': 'house',
  'منطار': 'lighthouse',
  'مهرج يلعب بالكرات': 'clown-juggling-balls',
  'نجار': 'carpenter',
  'نجمة حمراء': 'star',
  'نجمة صفراء ونجمة حمراء': 'star',
  'نجمة صفراء ونجمة زرقاء': 'star',
  'نجمة': 'star',
  'نخلة على الشجرة': 'palm-tree',
  'نخلة': 'palm-tree',
  'نخيل': 'palm-tree',
  'نقود': 'money',
  'نمر': 'tiger',
  'نهر': 'river',
  'وردة صفراء': 'flower',
  'وردة': 'flower',
  'ورقة صفراء': 'yellow',
  'ورقة بيضاء': 'white-carpet',
  'وسادة': 'pillow',
  'ولد يسبح في البحر': 'boy-swimming',
  'يجلس على الكرسي': 'sitting',
  'يحمل السلاح': 'weapon',
};

/**
 * Get English image file name from Arabic item name
 * @param {string} arabicName - Arabic item name
 * @returns {string} - English file name (without extension)
 */
export function getImageFileName(arabicName) {
  // Try exact match first
  if (arabicToEnglishMap[arabicName]) {
    return arabicToEnglishMap[arabicName];
  }
  
  // Try case-insensitive match
  const lowerName = arabicName.toLowerCase();
  for (const [key, value] of Object.entries(arabicToEnglishMap)) {
    if (key.toLowerCase() === lowerName) {
      return value;
    }
  }
  
  // Fallback: try to create a reasonable filename
  // Remove Arabic characters and create a slug
  const slug = arabicName
    .replace(/\s+/g, '-')
    .replace(/[^\w\-]/g, '')
    .toLowerCase();
  
  return slug || 'placeholder';
}

/**
 * Get full image path for an item
 * @param {string} arabicName - Arabic item name
 * @returns {string} - Full path to image file
 */
export function getImagePath(arabicName) {
  const fileName = getImageFileName(arabicName);
  return `/game-images/${fileName}.png`;
}

